export const activities: any = [
    {
        "groupName": "Trail Sisters",
        "isFitness": 1,
        "isSobrietyRelated": "",
        "isWomenFocused": "",
        "street1": "",
        "street2": "7100 Tramway Blvd NE",
        "city": "Albuquerque",
        "zipCode": 87122,
        "whenTheyMeet": "Check website calendar",
        "link": "https://communities.trailsisters.net/landing/",
        "description": "A trail running group focused on creating and inclusive and safe environment for women of all ages and fitness levels to run trails together in Albuquerque"
    },
    {
        "groupName": "Fleet Feet Sports",
        "isFitness": 1,
        "isSobrietyRelated": "",
        "isWomenFocused": "",
        "street1": "Fleet Feet Sports",
        "street2": "5701-R Wyoming Blvd NE",
        "city": "Albuquerque",
        "zipCode": 87109,
        "whenTheyMeet": "Tuesday 6:30pm  Saturday 8:45am",
        "link": "https://www.fleetfeet.com/s/albuquerque/training",
        "description": "Fleet Feet Sports's run/walk club is open to all abilities and participants are encouraged to bring a friend of like ability to ensure partnering within different paces."
    },
    {
        "groupName": "ABQ Road Runners Club",
        "isFitness": 1,
        "isSobrietyRelated": "",
        "isWomenFocused": "",
        "street1": "",
        "street2": "High Desert St",
        "city": "Albuquerque",
        "zipCode": 87111,
        "whenTheyMeet": "Monday & Wednesdays 6pm Saturday &  Sunday 7:30am",
        "link": "https://www.abqroadrunners.com/weekly-workouts.html",
        "description": "Founded in 1985, ARR is Albuquerque's oldest and largest open running club created for the promotion of health through running and social activity. Check schedule for Saturday runs, Sundays meet at Sandia Labs Credit Union near Trader Joe's, corner of Paseo del Norte and Ventura NE, Monday evening meets at southern Albuquerque Open Space at Indian School trailhead, Wednesday evenings meet at northern Albuquerque Open Spaces at the Michael Emery trailhead"
    },
    {
        "groupName": "Albuquerque Running Meetup",
        "isFitness": 1,
        "isSobrietyRelated": "",
        "isWomenFocused": "",
        "street1": "",
        "street2": "6440 Coors Blvd NW",
        "city": "Albuquerque",
        "zipCode": 87120,
        "whenTheyMeet": "Check meetup calendar",
        "link": "https://www.meetup.com/Albuquerque-Running-Meetup/",
        "description": "Meetup group focused on bringing together like minded people with an interest in the sport of running."
    },
    {
        "groupName": "The Albuquerque Hiking and Outdoor Meetup",
        "isFitness": 1,
        "isSobrietyRelated": "",
        "isWomenFocused": "",
        "street1": "",
        "street2": "19 Tres Pistolas Trail NE",
        "city": "Albuquerque",
        "zipCode": 87123,
        "whenTheyMeet": "Check meetup calendar",
        "link": "https://www.meetup.com/hiking-204/",
        "description": "Meetup group focused on bringing together local hiking enthusiasts who enjoy the wilderness and hiking in the mountains."
    },
    {
        "groupName": "NM Women Adventure Outdoors",
        "isFitness": 1,
        "isSobrietyRelated": "",
        "isWomenFocused": 1,
        "street1": "",
        "street2": "Continental Divide Trail",
        "city": "Glenwood",
        "zipCode": 88039,
        "whenTheyMeet": "Check meetup calendar",
        "link": "https://www.meetup.com/NM-Women-Go-Outdoor-Adventuring/",
        "description": "Meetup group focused on bringing together women who want to get outside to explore New Mexico"
    },
    {
        "groupName": "New Mexico Cross Country Ski Meetup Group",
        "isFitness": 1,
        "isSobrietyRelated": "",
        "isWomenFocused": "",
        "street1": "",
        "street2": "NM-536",
        "city": "Sandia Park",
        "zipCode": 87047,
        "whenTheyMeet": "Check meetup calendar",
        "link": "https://www.meetup.com/New-Mexico-Cross-Country-Ski-Meetup-Group/",
        "description": "Meetup group  that is an offshoot of the NM Cross Country Ski Club  focused on offering lower level outings so anyone can join in on the winder outdoor experience."
    },
    {
        "groupName": "Jornada hiking & Outdoors Club",
        "isFitness": 1,
        "isSobrietyRelated": "",
        "isWomenFocused": "",
        "street1": "La Llorona Park",
        "street2": "3440 W Picacho Ave",
        "city": "Las Cruces",
        "zipCode": 88007,
        "whenTheyMeet": "Check meetup calendar",
        "link": "https://www.meetup.com/jornadahikers/",
        "description": "Meetup group focused on connecting hiking and outdoor enthusiasts in the area of Las Cruces, NM (including Gila Wilderness, Deming, Alamogordo, Ruidoso, and Silver City), and El Paso, TX."
    },
    {
        "groupName": "Albuquerque Cyclists Club",
        "isFitness": 1,
        "isSobrietyRelated": "",
        "isWomenFocused": "",
        "street1": "",
        "street2": "Nature Trail",
        "city": "Albuquerque",
        "zipCode": 87114,
        "whenTheyMeet": "Check meetup calendar",
        "link": "https://www.meetup.com/albuquerque-cyclists-club",
        "description": "Meetup group focused on providing biking events where members can meet up with other road or mountain bicyclists to ride roads, paths and trails."
    },
    {
        "groupName": "New Mexico Stand Up Paddle Boarders",
        "isFitness": 1,
        "isSobrietyRelated": "",
        "isWomenFocused": "",
        "street1": "",
        "street2": "1101 NM-22",
        "city": "Cochiti",
        "zipCode": 87072,
        "whenTheyMeet": "Check meetup calendar",
        "link": "https://www.meetup.com/NM-Stand-Up-Paddle-Boarders/",
        "description": "Meetup group focused on connecting people to the paddling scene by providing year-around events promoting environmental awareness, conservation, good stewardship, as well as an active, healthy, outdoor lifestyle."
    },
    {
        "groupName": "WOC Run Burque",
        "isFitness": 1,
        "isSobrietyRelated": "",
        "isWomenFocused": 1,
        "street1": "Humble Coffee",
        "street2": "505 Central Ave NW",
        "city": "Albuquerque",
        "zipCode": 87102,
        "whenTheyMeet": "Friday",
        "link": "www.instagram.com/wocrunburque",
        "description": "Local women of color running group focused on uplifting, inspiring and motivating each other through. Join us on Fridays for coffee and running."
    },
    {
        "groupName": "Las Cruces Sahaja Meditation Meetup",
        "isFitness": 1,
        "isSobrietyRelated": "",
        "isWomenFocused": "",
        "street1": "Online,  check meetup calendar",
        "street2": "15 Bruins Ln",
        "city": "Las Cruces",
        "zipCode": 88005,
        "whenTheyMeet": "Saturdays 7:45pm & Sundays 7:45am",
        "link": "https://www.meetup.com/Las-Cruces-Sahaja-Meditation-Meetup",
        "description": "Meetup group  focused on Sahaja Meditation, a technique that helps reduce stress, increase wellness, improve focus , and helps people become more centered."
    },
    {
        "groupName": "NamaStaySober",
        "isFitness": 1,
        "isSobrietyRelated": 1,
        "isWomenFocused": "",
        "street1": "",
        "street2": "63 Lincoln Ave",
        "city": "Santa Fe",
        "zipCode": 87501,
        "whenTheyMeet": "Check meetup calendar",
        "link": "https://www.namastaysober.com/ https://www.meetup.com/NamaStay-Sober",
        "description": "Our mission is to aid those in recovery by reconnecting their bodies and minds through affordable yoga, fitness, meditation and wellness-focused community events. By becoming a member of our community participants are given access to create a new and healthy lifestyle alongside their peers.�"
    },
    {
        "groupName": "New Mexico Meditation Meet up",
        "isFitness": 1,
        "isSobrietyRelated": "",
        "isWomenFocused": "",
        "street1": "",
        "street2": "490 Old Santa Fe Trail",
        "city": "Santa Fe",
        "zipCode": 87501,
        "whenTheyMeet": "2nd Sundays of the month",
        "link": "https://www.meetup.com/NM-Meditation-Meetup/",
        "description": "Email Inessa inessa45ATgmail.com for location. Meetup group focused on supporting the New Mexico Meditation Community by providing meditation events and training."
    },
    {
        "groupName": "Celebrate Recovery",
        "isFitness": "",
        "isSobrietyRelated": 1,
        "isWomenFocused": "",
        "street1": "East Gate Church",
        "street2": "12120 Copper Ave",
        "city": "Albuquerque",
        "zipCode": 87123,
        "whenTheyMeet": "Friday 6:15pm",
        "link": "https://www.celebraterecovery.com/",
        "description": "Contact: Georgina Fourzan geoduenas@yahoo.com. Celebrate Recovery is a Christ-centered, 12 step recovery program, and safe place for anyone struggling with hurt, pain or addiction of any kind."
    },
    {
        "groupName": "Celebrate Recovery",
        "isFitness": "",
        "isSobrietyRelated": 1,
        "isWomenFocused": "",
        "street1": "Grace Outreach Center",
        "street2": "2900 Southern Blvd",
        "city": "Rio Rancho",
        "zipCode": 87124,
        "whenTheyMeet": "Friday 6:15pm",
        "link": "https://www.celebraterecovery.com/",
        "description": "Contact: Miles Melton homesnv@msn.com. Celebrate Recovery is a Christ-centered, 12 step recovery program, and safe place for anyone struggling with hurt, pain or addiction of any kind."
    },
    {
        "groupName": "Celebrate Recovery",
        "isFitness": "",
        "isSobrietyRelated": 1,
        "isWomenFocused": "",
        "street1": "River Crossing",
        "street2": "1950 Sudderth Dr",
        "city": "Ruidoso",
        "zipCode": 88345,
        "whenTheyMeet": "Monday 6pm",
        "link": "https://www.celebraterecovery.com/",
        "description": "Contact: Cory Myers myersl95@yahoo.com. Celebrate Recovery is a Christ-centered, 12 step recovery program, and safe place for anyone struggling with hurt, pain or addiction of any kind."
    },
    {
        "groupName": "Celebrate Recovery",
        "isFitness": "",
        "isSobrietyRelated": 1,
        "isWomenFocused": "",
        "street1": "Carrizozo CR",
        "street2": "1010 13th Street",
        "city": "Carrizozo",
        "zipCode": 88301,
        "whenTheyMeet": "Thursday 6pm",
        "link": "https://www.celebraterecovery.com/",
        "description": "Contact: Barbara Buttram zozodifference@gmail.com. Celebrate Recovery is a Christ-centered, 12 step recovery program, and safe place for anyone struggling with hurt, pain or addiction of any kind."
    },
    {
        "groupName": "Celebrate Recovery",
        "isFitness": "",
        "isSobrietyRelated": 1,
        "isWomenFocused": "",
        "street1": "Trinity on the Hill Episcopal Church",
        "street2": "3900 Trinity Dr",
        "city": "Los Alamos",
        "zipCode": 87544,
        "whenTheyMeet": "Thursday 7pm",
        "link": "https://www.celebraterecovery.com/",
        "description": "Contact: Robert Vigil rvigilpainting@msn.com. Celebrate Recovery is a Christ-centered, 12 step recovery program, and safe place for anyone struggling with hurt, pain or addiction of any kind."
    },
    {
        "groupName": "Celebrate Recovery",
        "isFitness": "",
        "isSobrietyRelated": 1,
        "isWomenFocused": "",
        "street1": "Real Life Church",
        "street2": "1040 El Paseo Rd",
        "city": "Las Cruces",
        "zipCode": 88005,
        "whenTheyMeet": "Monday 6:30pm",
        "link": "https://www.celebraterecovery.com/",
        "description": "Contact: Dennis Gallegos psthomas8111@gmail.com. Celebrate Recovery is a Christ-centered, 12 step recovery program, and safe place for anyone struggling with hurt, pain or addiction of any kind."
    },
    {
        "groupName": "Women for Sobriety",
        "isFitness": "",
        "isSobrietyRelated": 1,
        "isWomenFocused": 1,
        "street1": "",
        "street2": "8100 Eubank Blvd NE",
        "city": "Albuquerque",
        "zipCode": 87122,
        "whenTheyMeet": "Wednesday 5:30pm",
        "link": "https://womenforsobriety.org/",
        "description": "Email 1104@womenforsobriety.org for meeting address. Women for Sobriety, Inc., is a non-profit organization dedicated to helping women discover a happy New Life in recovery from Substance Use Disorders."
    },
    {
        "groupName": "SMART Recovery",
        "isFitness": "",
        "isSobrietyRelated": 1,
        "isWomenFocused": "",
        "street1": "",
        "street2": "105 15th Street",
        "city": "Los Alamos",
        "zipCode": 87544,
        "whenTheyMeet": "Thursdays 5:30-7pm",
        "link": "https://www.smartrecoverytest.org/local/meeting/los-alamos-new-mexico-thursday-530-pm-to-700-pm/",
        "description": "Self-Management and Recovery Training (SMART) is a global community of mutual-support groups that are open to anyone seeking science-based, self-empowered addiction recovery."
    },
    {
        "groupName": "SMART Recovery",
        "isFitness": "",
        "isSobrietyRelated": 1,
        "isWomenFocused": "",
        "street1": "",
        "street2": "2100 Aztec Rd NE, Suite A",
        "city": "Albuquerque",
        "zipCode": 87107,
        "whenTheyMeet": "Wednesday 5:30-7pm",
        "link": "https://www.smartrecoverytest.org/local/meeting/albuquerque-new-mexico-wednesday-530-pm-to-700-pm/",
        "description": "Self-Management and Recovery Training (SMART) is a global community of mutual-support groups that are open to anyone seeking science-based, self-empowered addiction recovery."
    },
    {
        "groupName": "SMART Recovery",
        "isFitness": "",
        "isSobrietyRelated": 1,
        "isWomenFocused": "",
        "street1": "",
        "street2": "4801 Beckner Rd, Room 511",
        "city": "Santa Fe",
        "zipCode": 87507,
        "whenTheyMeet": "Thursday 6-7pm",
        "link": "https://www.smartrecoverytest.org/local/meeting/santa-fe-new-mexico-thursday-600-pm-to-700-pm/",
        "description": "Self-Management and Recovery Training (SMART) is a global community of mutual-support groups that are open to anyone seeking science-based, self-empowered addiction recovery."
    }
]